name: Build www.ruma.io
on:
  push:
    branches:
      - source
jobs:
  deploy:
    name: Build and deploy the site
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repository
      env:
        REPOSITORY: ${{ github.repository }}
      run: |
        git clone "https://github.com/$REPOSITORY"
    - name: Download Zola
      run: |
        version='v0.11.0'
        archive="zola-${version}-x86_64-unknown-linux-gnu.tar.gz"
        curl -L "https://github.com/getzola/zola/releases/download/${version}/${archive}" -o "$archive"
        tar xf "$archive"
    - name: Build the site
      run: |
        ./zola build
    - name: Deploy the site
      working-directory: ./public
      env:
        DEPLOY_SECRET_KEY: ${{ secrets.DEPLOY_SECRET_KEY }}
      run: |
        echo "$DEPLOY_SECRET_KEY" > ~/.ssh/id_ed25519

        echo 'Host *' >> ~/.ssh/config
        echo '    StrictHostKeyChecking=no' >> ~/.ssh/config

        git config --global user.email "noreply@ruma.io"
        git config --global user.name "CI"
        git init
        git add -A
        git commit -m "Add files generated by zola"
        git push -f git@github.com:ruma/ruma.github.io
